---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /.config/obsidian:/config
    ports:
      - 3033:3000
      - 3034:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - homelab-net