version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_NUM_GPU=1
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_GPU_MEMORY_FRACTION=0.9
    restart: unless-stopped
    networks:
      openwebui-network:
        aliases:
          - ollama

volumes:
  ollama-data:

networks:
  openwebui-network:
    external: true
