version: '3.8'

services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    ports:
      - "61208:61208"  # Web UI
    restart: unless-stopped
    network_mode: "host"  # easier for GPU access
    environment:
      - GLANCES_OPT=-w
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
