version: '3.8'
services:
  # Loki - Log aggregation (like a lightweight SIEM)
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - homelab-net

  # Grafana - Beautiful dashboards and visualization
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - homelab-net
    depends_on:
      - loki

promtail:
  image: grafana/promtail:2.9.4
  container_name: promtail
  restart: unless-stopped
  volumes:
    - /var/log:/var/log:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
  command: -config.file=/etc/promtail/config.yml
  configs:
    - source: promtail_config
      target: /etc/promtail/config.yml
  networks:
    - homelab-net
  depends_on:
    - loki

# Add this configs section at the bottom with your volumes and networks:
configs:
  promtail_config:
    content: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0

      positions:
        filename: /tmp/positions.yaml

      clients:
        - url: http://loki:3100/loki/api/v1/push

      scrape_configs:
        - job_name: system
          static_configs:
            - targets:
                - localhost
              labels:
                job: system
                __path__: /var/log/*.log
                __path__: /var/log/**/*.log

        - job_name: docker
          static_configs:
            - targets:
                - localhost
              labels:
                job: docker
                __path__: /var/lib/docker/containers/*/*-json.log

        - job_name: auth
          static_configs:
            - targets:
                - localhost
              labels:
                job: auth
                __path__: /var/log/auth.log

        - job_name: tunnels
          static_configs:
            - targets:
                - localhost
              labels:
                job: tunnels
                __path__: /var/log/*tunnel*.log
                __path__: /var/log/*vpn*.log
                __path__: /var/log/*wireguard*.log

volumes:
  grafana_data:
    driver: local

networks:
  homelab-net:
    external: true